### ISSUE TITLE
 Usage of 'EdgeDriver' Service along with 'selenium-standalone' to run firefox,chrome,edgechromium parallely ?

### ISSUE THREAD

**Issue by chandrasekhar11** [webdriverio-community/wdio-edgedriver-service#2]
when using 'selenium-standalone' and 'edgedriver' service together to run all chrome,firefox,edgechromium browsers parallely,

Only Chromium edge browser is working.

for Chrome and firefox, getting error no capabilities found

Error :

Request failed with status 500 due to session not created: No matching capabilities found
[1-0] 2020-07-13T09:10:50.874Z INFO webdriver: Retrying 1/3
2020-07-13T09:10:50.875Z INFO webdriver: [POST] http://localhost:51573/session
2020-07-13T09:10:50.875Z INFO webdriver: DATA {
  capabilities: { alwaysMatch: { browserName: 'Chrome' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'Chrome' }

wdio config:
 capabilities: [{
    
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 1,
        //
        browserName: 'MicrosoftEdge',
        

        // If outputDir is provided WebdriverIO can capture driver session logs
        // it is possible to configure which logTypes to include/exclude.
        // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
        // excludeDriverLogs: ['bugreport', 'server'],
    },
    {
        maxInstances:1,
        browserName:'Chrome'
    }
    
-------------------------------------------------------------

    services:  ['selenium-standalone','edgedriver'],

**Comment by christian-bromann** [comment]
@chandrasekhar11 there is no reason to run both together because the Selenium Standalone server is able to spin up Edgedriver sessions for you. Please let me know if you have any further questions.
