### ISSUE TITLE
Doesn't work - old driver used?

### ISSUE THREAD

**Issue by j4ckp0t85** [webdriverio-community/wdio-edgedriver-service#3]
I've tried both on windows and mac, it doesn't work.

Maybe using this new package [link](https://www.npmjs.com/package/ms-chromium-edge-driver)?

Notice that the driver must be first installed as stated on readme, then there is a property to get the path.

**Comment by RafalSkorka** [comment]
this service is for getting the old edge driver, not the chromium-based edge.

**Comment by j4ckp0t85** [comment]
Do you have in plan to make a version for chromium Edge? Since old Is almost abandoned

**Comment by RafalSkorka** [comment]
for chromium edge you should be able to use the chrome driver since it is really the same code, just providing the path to it in the goog:chromeOptions.binary option.

**Comment by j4ckp0t85** [comment]
Still no luck. I ended up writing hooks to launch the driver on wdio conf file (i don't know why but it does't work using a custom service on last version available, but that's another topic)

**Comment by christian-bromann** [comment]
Any help on this would be much appreciated 🙏

**Comment by christian-bromann** [comment]
@j4ckp0t85 can you retry with latest released version? This should be fixed, if not I am happy to reopen.
